### ISSUE TITLE
These prompts are not optimised for Claude

### ISSUE THREAD

**Issue by EngineeringErgonomics** [langgptai/awesome-claude-prompts#3]
For example, Claude will refuse the Mr Randeer prompt. You can't simply copy a ChatGPT prompt and call it a Claude prompt. They are very different systems and require different prompting approaches.

**Comment by yzfly** [comment]
These prompts performed well when they were included, but the model changes rapidly, and there are differences in performance across different versions. These prompts are provided merely as a reference. In any case, for engineering applications, you should consider adjusting them to fit your specific scenario.

**Comment by EngineeringErgonomics** [comment]
I think this is not true. I have a lot of experience with Claude, and these would never have worked. It's poor form to call these awesome Claude prompts and then simply recycle ChatGPT prompts. Any prompt engineer will tell you the model differences are enough to require a customised approach. 

I think instead of ignoring feedback, you should curate this repo to be a useful starting point for Claude prompt engineers.

**Comment by promptagi** [comment]
It's irresponsible to say that these have never been worked. Have you really used Claude for a long time? 

Take the Mr.-Ranedeer-AI-Tutor example, you can also check:

https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor

<img width="763" alt="图片" src="https://github.com/user-attachments/assets/7ba51140-0b7a-4fb9-b932-2c61cd7bce7b">

It can be also checked in:

https://x.com/yupiop12/status/1661388589572169736

Compared to baseless criticism, at the very least, please post your usage effect and evaluate the situation, rather than shifting the testing cost. We reject freelancing and baseless negative criticism.

We have been using claude since its release, and this repository is mainly for collecting personal learning materials. 
Our claude usage experience may not be as extensive as yours, so we welcome you to contribute your time and energy to maintain it together.
